//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacionNG
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBS_NEIGHBORFOOD2Entities : DbContext
    {
        public DBS_NEIGHBORFOOD2Entities()
            : base("name=DBS_NEIGHBORFOOD2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_Administrador> TBL_Administrador { get; set; }
        public virtual DbSet<TBL_Cliente> TBL_Cliente { get; set; }
        public virtual DbSet<TBL_Menu> TBL_Menu { get; set; }
        public virtual DbSet<TBL_Plato> TBL_Plato { get; set; }
        public virtual DbSet<TBL_Preferencias> TBL_Preferencias { get; set; }
        public virtual DbSet<TBL_Promociones> TBL_Promociones { get; set; }
        public virtual DbSet<TBL_Puntos> TBL_Puntos { get; set; }
        public virtual DbSet<TBL_Resena> TBL_Resena { get; set; }
        public virtual DbSet<TBL_Restaurante> TBL_Restaurante { get; set; }
        public virtual DbSet<TBL_SEDE> TBL_SEDE { get; set; }
    }
}
