//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacionNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Cliente()
        {
            this.TBL_Resena = new HashSet<TBL_Resena>();
            this.TBL_Preferencias = new HashSet<TBL_Preferencias>();
            this.TBL_Puntos = new HashSet<TBL_Puntos>();
            this.TBL_Resena1 = new HashSet<TBL_Resena>();
        }
    
        public int PK_Cedula_Cliente { get; set; }
        public string CLI_Nombre { get; set; }
        public string CLI_Apellido { get; set; }
        public string CLI_Genero { get; set; }
        public string CLI_CorreoElectronico { get; set; }
        public System.DateTime CLI_FechaNacimiento { get; set; }
        public string CLI_Ciudad { get; set; }
        public string CLI_Barrio { get; set; }
        public int CLI_Telefono { get; set; }
        public string CLI_Contrasena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Resena> TBL_Resena { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Preferencias> TBL_Preferencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Puntos> TBL_Puntos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Resena> TBL_Resena1 { get; set; }
    }
}
