//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacionNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Resena
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Resena()
        {
            this.TBL_Cliente1 = new HashSet<TBL_Cliente>();
        }
    
        public int PK_CodigoReseña { get; set; }
        public System.DateTime RES_Fecha { get; set; }
        public double RES_Calificacion { get; set; }
        public string RES_Opinion { get; set; }
        public int FK_CodCliente { get; set; }
        public int FK_CodRestaurante { get; set; }
    
        public virtual TBL_Cliente TBL_Cliente { get; set; }
        public virtual TBL_Restaurante TBL_Restaurante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Cliente> TBL_Cliente1 { get; set; }

       
    }
}
