//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacionNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Restaurante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Restaurante()
        {
            this.TBL_Administrador = new HashSet<TBL_Administrador>();
            this.TBL_Preferencias = new HashSet<TBL_Preferencias>();
            this.TBL_Resena = new HashSet<TBL_Resena>();
            this.TBL_Promociones = new HashSet<TBL_Promociones>();
            this.TBL_SEDE = new HashSet<TBL_SEDE>();
        }
    
        public int PK_CodigoRestaurante { get; set; }
        public string RESTA_Nombre { get; set; }
        public int RESTA_Telefono { get; set; }
        public string RESTA_Correo { get; set; }
        public Nullable<int> FK_CodigoAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Administrador> TBL_Administrador { get; set; }
        public virtual TBL_Administrador TBL_Administrador1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Preferencias> TBL_Preferencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Resena> TBL_Resena { get; set; }
        public virtual TBL_Restaurante TBL_Restaurante1 { get; set; }
        public virtual TBL_Restaurante TBL_Restaurante2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Promociones> TBL_Promociones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SEDE> TBL_SEDE { get; set; }
    }
}
