//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacionNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Plato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Plato()
        {
            this.TBL_Preferencias = new HashSet<TBL_Preferencias>();
            this.TBL_Menu = new HashSet<TBL_Menu>();
        }
    
        public int PK_CodigoPlato { get; set; }
        public string PLA_NombrePlato { get; set; }
        public double PLA_Precio { get; set; }
        public string PLA_Descripcion { get; set; }
        public string PLA_Ingredientes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Preferencias> TBL_Preferencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Menu> TBL_Menu { get; set; }
    }
}
