//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacionNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Administrador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Administrador()
        {
            this.TBL_Restaurante1 = new HashSet<TBL_Restaurante>();
        }
    
        public int PK_Cedula_Administrador { get; set; }
        public string ADM_Nombre { get; set; }
        public string ADM_Apellido { get; set; }
        public string ADM_Genero { get; set; }
        public string ADM_CorreoElectronico { get; set; }
        public string ADM_Contrasena { get; set; }
        public int ADM_Telefono { get; set; }
        public int FK_CodRestaurante { get; set; }
    
        public virtual TBL_Restaurante TBL_Restaurante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Restaurante> TBL_Restaurante1 { get; set; }
    }
}
