//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacionNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Puntos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Puntos()
        {
            this.TBL_Cliente = new HashSet<TBL_Cliente>();
        }
    
        public int PK_CodigoPuntos { get; set; }
        public Nullable<int> PUN_Cantidad { get; set; }
        public System.DateTime PUN_FechaCreacion { get; set; }
        public Nullable<System.DateTime> PUN_FechaCaducidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Cliente> TBL_Cliente { get; set; }
    }
}
